### ISSUE TITLE
Cannot start module with angulartics

### ISSUE THREAD

**Issue by baierjak** [luisfarzati/angulartics#137]
Hey Guys, i have problem with adding angulartics.

In my app.js I just added that two dependencies (angulartics and angulartics and the last one) you can see:
var smsApp = angular.module('smsApp', [
  'ngRoute',
  'smsControllers',
  'smsFilters',
  'google-maps',
  'pascalprecht.translate',
  'angulartics',
  'angulartics.google.analytics',
]);

and then in my index.html I added:
< script src="./js/angulartics.js"></script >
< script src="./js/angulartics-ga.js"></script > ---- ways to this files are ok

but when I want to create that modul with:
var injector = angular.injector(['smsApp', 'ng']);

I got this error:
Uncaught Error: [$injector:unpr] http://errors.angularjs.org/1.2.15/$injector/unpr?p0=%24rootElementProvider%20%3C-%20%24rootElement%20%3C-%20%24location 

and without anguartics it goes well! Please help me :) thankx

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss.
