### ISSUE TITLE
Feature Request: Set default GA Category

### ISSUE THREAD

**Issue by NewMediaRoc** [luisfarzati/angulartics#14]
Not sure how you would do it, but it would be awesome to be able to set a default Category for any tracking tags within a controller or within a module. It would help cut down on repetition of the analytics-category="" attribute. It would also help to allow you to add the analytics directive to templates for other directives and to simply set the category at the controller-level. This would minimize repeated code by keeping the tracking tag with the component, while simply switching out the category to signify the different location of the component.

**Comment by trolleycrash** [comment]
I suggest at least one of two changes:

1) Setting the default event category to "Event" in the case that neither the `analytics-category` directive, nor any other method (like the HTML comment method described above by @luisfarzati) are used
2) Some debugger output for the developer who is wondering why their event isn't being tracked. Like "Google Analytics requires an Event Category"

It seems to me that simply failing without error (as is the case at the beginning of `angulartics.google.analytics.$analyticsProvider.registerEventTrack`) makes the problem of a missing event category very difficult to identify.

**Comment by luisfarzati** [comment]
Fixed by #334
