### ISSUE TITLE
Timeout for certain clicks?

### ISSUE THREAD

**Issue by nneal** [luisfarzati/angulartics#148]
Would there be any interest in adding an optional timeout for the "analytics-*" directives? I'm using Angular + Rails, so when I do page reloads, the click on buttons/links/etc is not recorded because the page changes before the request is fired. Is there a way to add a timeout with the current library? I didn't see a way but wanted to check. Otherwise, it would be a great addition.

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss.
