### ISSUE TITLE
Dont work in cordova + ionic | Module 'angulartics' is not available

### ISSUE THREAD

**Issue by bcarvalho89** [luisfarzati/angulartics#171]
I'm trying to deploy a project with cordova + ionic, but without success. 
Includes angulartics-ga-cordova.js in my index file and place the following tag at the end of the body with script tags: 
<pre>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-48718316-2');
	</pre>
This is my app.js file: 
<pre>
var starter = angular.module('starter', ['angulartics', 'angulartics.google.analytics.cordova', 'ionic', 'starter.controllers', 'starter.services']);

starter.config(function ($analyticsProvider) {
	$analyticsProvider.firstPageview(true); /* Records pages that don't use $state or $route */
	$analyticsProvider.withAutoBase(true);  /* Records full path */
	console.log("Pass here");
})

starter.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
    // for form inputs)
    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
    }
    if(window.StatusBar) {
      // org.apache.cordova.statusbar required
      StatusBar.styleDefault();
    }
  });
})
</pre>

The message I get in the console is:
<pre>
Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module angulartics due to:
Error: [$injector:nomod] Module 'angulartics' is not available! You either misspelled the...<omitted>...1) 
</pre>

Did I do something wrong? 

Thank you.

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss.
