### ISSUE TITLE
Angulartics reports 2 different paths for HTML5mode routing.

### ISSUE THREAD

**Issue by danghoa1** [luisfarzati/angulartics#192]
I have a website where all of my pages are under /us path.  For example:

www.example.com/us/home    (Main page)
www.example.com/us/home/page-a
www.example.com/us/home/page-b

So the routing starts after /us.  I.E., in hashbang mode, the pages above would be:

www.example.com/us/#!/home    (Main page)
www.example.com/us/#!/home/page-a
www.example.com/us/#!/home/page-b

Angulartics is expected to register page views with the following paths:

/us/home
/us/home/page-a
/us/home/page-b

Instead, Angulartics returns 2 different paths for the same page (the '/us' part is sometimes missing)

/us/home
/home
/us/home/page-a
/home/page-a
/us/home/page-b
/home/page-b

The version im running is 0.16.5

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss.
