### ISSUE TITLE
Angulartics preventing Select2 model from updating

### ISSUE THREAD

**Issue by Soviut** [luisfarzati/angulartics#195]
I'm using Select2 to style a dropdown select box. It emits custom events from the original hidden select element. In my case, I wanted to track when the menu is opened so I did the following. Select2 emits a `select2-opening` event which Angulartics was able to capture in `analytics-on`:

```
<select id="builder-primary-character" ui-select2="selectOptions" ng-model="primaryCharacter" analytics-on="select2-opening" analytics-event="click" analytics-category="scenebuilder" analytics-label="character1">
```
 The problem is that Select2 no longer updates the model. When I remove the `analytics-on` directive the model starts updating again.

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss.
