### ISSUE TITLE
Mixpanel: disable "Page Viewed" event tracking

### ISSUE THREAD

**Issue by gpstmp** [luisfarzati/angulartics#212]
I want to completely disable "Page Viewed" event tracking. I can see it here: https://github.com/luisfarzati/angulartics/blob/master/src/angulartics-mixpanel.js#L50 but cannot find the way to disable it.

Thank you.

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss this issue.

**Comment by j-low** [comment]
Have there been any updates re: turning off page view tracking only for specified services?
