### ISSUE TITLE
Google Analytics tracking as a "mobile app"

### ISSUE THREAD

**Issue by rayshan** [luisfarzati/angulartics#227]
GA allows user to set up a property as a "mobile app" instead of a website, however it can be used for web apps as well. It allows tracking more like a typical app, with concepts like screenviews instead of pageviews, and additional dimensions such as app version. E.g.:
https://developers.google.com/analytics/devguides/collection/protocol/v1/devguide#screenView

Can angulartics accommodate this kind of tracking in additional to typical GA website tracking?

**Comment by luisfarzati** [comment]
#284 solves this but needs to be resubmitted at [the new GA plugin repo](https://github.com/angulartics/angulartics-google-analytics)
