### ISSUE TITLE
Double page views with multiple angular.module

### ISSUE THREAD

**Issue by daniel-obadia** [luisfarzati/angulartics#228]
Hi!

We just recently found the https://github.com/luisfarzati/angulartics/issues/97 bug as we had really low bounce rates on our app. Once we upgraded to the latest version (v0.17.0) that had the fix for this we thought all was going to be fixed.

As it turned out, it didn't get fixed and here's why we are getting double page views : 

Our AngularJS app is using several "angular.module" with one of them being the main application.

Heres the structure : 
Main :
var app = angular.module("myApp", ['ngCookies', 'bardo.directives', 'leaflet-directive', 'ngSanitize', 'vr.directives.slider', 'ui.router', 'ui.bootstrap.modal', 'ui.bootstrap.popover', 'ngRoute', 'angulartics', 'angulartics.google.analytics', 'angular-flexslider']);

Secondary : 
var mySearch = angular.module("mySearch", ['myApp', 'ui.router', 'confirmButton', 'ngRoute'])
Here we define several states and URLS...

As you can see the mySearch app depends on "myApp" app. It looks as if the use of two angular.modules makes Angulartics send double page views.

As soon as we add "$analyticsProvider.virtualPageviews(false);" to the seconday "mySearch" module it stops sending the double page views.

Has anyone encountered this and what would be a long term fix for this?

Thanks

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss.
