### ISSUE TITLE
How to send google Analytics campaign?

### ISSUE THREAD

**Issue by steve21124** [luisfarzati/angulartics#235]
To track google analytics campaign will use this url
https://www.domainname.com?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

how to send google campaign?

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss.

**Comment by awebdeveloper** [comment]
any updates from anyone
