### ISSUE TITLE
how do i pass identity to segment.io?

### ISSUE THREAD

**Issue by altsang** [luisfarzati/angulartics#243]
I'm using segment.io and want to pass identity, I'm using integrations to Mixpanel and Intercom.io

**Comment by bensquire** [comment]
@altsang did you ever find a solution to this? In our code:

     $analytics.setUserProperties(objectProperties);

did the job.

**Comment by altsang** [comment]
I did not, thanks @bensquire ! will give this a try

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss.
