### ISSUE TITLE
put samples folder in bower's ignore folder

### ISSUE THREAD

**Issue by mikeatlas** [luisfarzati/angulartics#244]
Otherwise they inadvertently get packaged up and pulled along with main assets downstream (such as in rails-assets)

See: https://github.com/rails-assets/rails-assets/issues/196

**Comment by luisfarzati** [comment]
Sorry for the very late response, but this is being undertaken now with the moving of plugins to their own repo. See #377 and https://github.com/angulartics/angulartics-google-analytics/blob/master/bower.json#L11
