### ISSUE TITLE
UI-Router & Woopra Issues

### ISSUE THREAD

**Issue by nowned** [luisfarzati/angulartics#245]
It looks like UI-Router and Woopra have some weird issues when they are combined.

We are loading both Google Analytics as well as Woopra and I can see all of our GA calls going through just fine, but Woopra isn't making any at all.

Using Angulartics 0.17.1, UI-Router 0.2.12, Angular 1.3.2
Let me know if you need any more details to replicate

**Comment by luisfarzati** [comment]
Closing old issues. Please feel free to reopen if you still interested in this case.
