### ISSUE TITLE
Omniture page tracking not getting path

### ISSUE THREAD

**Issue by mmealling** [luisfarzati/angulartics#248]
We have an SPA and we have set trackRelativePath to true but the client is only seeing "app.html" for all of its page load metrics. Looking at the code it appears that s.t is called with the path as an array: 

  s.t([path]);

But looking at this from Adobe:

https://marketing.adobe.com/developer/en_US/blog/omniture-tip-s-and-tricks-the-custom-object-parameter

It appears that it should be this:

s.t({pageName: path});

instead. I'm really new to both Angulartics and Omniture so I'm posting this as an issue but I could just be very very wrong.

**Comment by SuperheroicCoding** [comment]
I agree that that fix worked for me.
