### ISSUE TITLE
Social Tracking 

### ISSUE THREAD

**Issue by alexreardon** [luisfarzati/angulartics#252]
As it currently stands, there is no way to utilise google social sharing using angulartics. 

Google social events
https://developers.google.com/analytics/devguides/collection/gajs/gaTrackingSocial

My proposal is the write a small change to `angulartics-ga.js` to include a `registerSocialEventTrack` handler. I could do this in a PR. I don't want to go to the trouble if the moderators are not keen

**Comment by timelf123** [comment]
@alexreardon This sounds great! I'd love to see your addition when it is ready

**Comment by mrowles** [comment]
+1

**Comment by luisfarzati** [comment]
Closing this for now, if anyone want to submit a PR then I'll be happy to merge it.
