### ISSUE TITLE
Unable to add newest version to rails-assets.org

### ISSUE THREAD

**Issue by rbloor-mdsol** [luisfarzati/angulartics#254]
![image](https://cloud.githubusercontent.com/assets/2085764/5267317/17a09be2-7a1e-11e4-8530-87088794e428.png)

**Comment by crearc** [comment]
Package is now available from adding a release in the SHA-1 repo. https://github.com/linkgod/SHA-1/pull/3

**Comment by rbloor-mdsol** [comment]
@crearc thank you!

**Comment by timelf123** [comment]
Thanks all!
