### ISSUE TITLE
Support for Google Tag Manager with Cordova

### ISSUE THREAD

**Issue by kraihn** [luisfarzati/angulartics#258]
I'm beginning work on a Cordova plugin to support Google Tag Manager, and wanted to open this issue to allow for discussion around adding it to Angulartics. I plan to build it as a mirror to the current GTM plugin.

I've used angulartics-ga-cordova.js as a baseline for my Angulartics component.

My use case is that I'm on a team building a hybrid mobile app that is also deployed as a responsive website. We're already using Angulartics with success on our web portion, but are looking for a mobile app solution. Ideally without having to reconfigure much between the deploys.

**Comment by izhekov** [comment]
How this plugin interacts with angulartics-gtm-cordova.js? I cannot find any information regarding its usage.
