### ISSUE TITLE
bower install failure

### ISSUE THREAD

**Issue by chenliu0831** [luisfarzati/angulartics#265]
```
bower jquery-waypoints#~v2.0.3   ENORESTARGET No tag found that was able to satisfy ~v2.0.3

Additional error details:
No versions found in git://github.com/imakewebthings/jquery-waypoints.git
rake aborted!
```

**Comment by matmar10** [comment]
This is still an issue. I got this today:

Additional error details:
fatal: remote error: 
  Repository `imakewebthings/waypoints' is disabled. Please ask the owner to check their account.

**Comment by timelf123** [comment]
Try `bower cache clean` then install as usual

**Comment by luisfarzati** [comment]
Closing now -- if you still have this issue please feel free to reopen.
