### ISSUE TITLE
Google Analytics (Universal): events report URLs without hash

### ISSUE THREAD

**Issue by jirihelmich** [luisfarzati/angulartics#271]
One is unable to set UGA in a way that it automatically reports hash fragment in URL while reporting an event. It needs to be explicitly reported:

http://stackoverflow.com/a/20632245/643497

```
ga('send', 'event', 'category', 'action', {'page': '/my-new-page'});
```

It should be just another parameter here, I think:

https://github.com/luisfarzati/angulartics/blob/master/src/angulartics-ga.js#L73

I would do a PR, but not sure of a correct way withing angulartics, how to obtain the full URL. I would simply use `$location`.

**Comment by jirihelmich** [comment]
Hi, could you at least comment on using $location for this? if it is acceptable, I will do a PR, because I really need this fixed :-)

**Comment by raduvanciu** [comment]
One patch may be to add 
<code>page: properties.page || null</code>
at 
https://github.com/luisfarzati/angulartics/blob/master/src/angulartics-ga.js#L71

as in 
<code>
		`var eventOptions = {
		  eventCategory: properties.category || null,
		  eventAction: action || null,
		  eventLabel: properties.label ||  null,
		  eventValue: properties.value || null,
		  nonInteraction: properties.noninteraction || null,
		  page: properties.page || null
	 };`
</code>

Then, to send the page attribute to UGA:

<code>
`<a> ... analytics-on="click" ... analytics-page="/my-new-page" </a>`
</code>

I hope you will include such a patch in the next version
