### ISSUE TITLE
No Documentation on User Tracking

### ISSUE THREAD

**Issue by ajbraus** [luisfarzati/angulartics#276]
How do you implement user tracking on GA?

**Comment by Fonger** [comment]
+1
This feature is very important, I can't find an equivalent way to do this in Angulartics.
```js
ga('create', 'UA-XXXXXXXX-X',{ 'userId': '123456' });
```

**Comment by commaander** [comment]
+1 for mixpanel

**Comment by dkarter** [comment]
:+1: I see this in the code 

```javascript
// Segment Identify Method
      // https://segment.com/docs/libraries/analytics.js/#identify
      // analytics.identify([userId], [traits], [options], [callback]);
      $analyticsProvider.registerSetUserProperties(function (userId, traits, options, callback) {
        try {
          analytics.identify(userId, traits, options, callback);
        } catch (e) {
          if (!(e instanceof ReferenceError)) {
            throw e;
          }
        }
      });

      // Segment Identify Method
      // https://segment.com/docs/libraries/analytics.js/#identify
      // analytics.identify([userId], [traits], [options], [callback]);
      $analyticsProvider.registerSetUserPropertiesOnce(function (userId, traits, options, callback) {
        try {
          analytics.identify(userId, traits, options, callback);
        } catch (e) {
          if (!(e instanceof ReferenceError)) {
            throw e;
          }
        }
      });
```

For segment.io but not sure how to use it. If I had to guess it's probably $analytics.setUserProperties(....). I haven't tested it but the logic follows: considering there are two other methods in this file on the provider: `registerPageTrack`, `registerEventTrack`. To call those one uses `$analytics.eventTrack(...)` etc. therefore it appears that eliminating the register part of the function you should be able to call `$analytics.setUserProperties(....)`.

@Normalised Can you confirm? It appears you implemented these.

**Comment by dkarter** [comment]
![never mind](https://www.dropbox.com/s/ggoh9r0nw735mbo/Screenshot%202015-02-11%2015.35.29.png?dl=1)

Never mind. Confirmed. :smile:

**Comment by Normalised** [comment]
Glad you found it :)

If you look here

https://github.com/luisfarzati/angulartics/blob/master/src/angulartics.js#L43

you'll see which handlers a particular provider can register themselves for.

```javascript
  var knownHandlers = [
    'pageTrack',
    'eventTrack',
    'setAlias',
    'setUsername',
    'setAlias',
    'setUserProperties',
    'setUserPropertiesOnce',
    'setSuperProperties',
    'setSuperPropertiesOnce'
  ];
```

The setUserProperties is just a straight mapping onto the segment API :

https://segment.com/docs/libraries/analytics.js/#identify

**Comment by chrisjbrown** [comment]
+1 for mixpanel people
