### ISSUE TITLE
Angulartics doesn't allow route navigation to occur in 

### ISSUE THREAD

**Issue by ElanHasson** [luisfarzati/angulartics#281]
I'm using GTM plugin,  AngularJS v1.3.8, UI Router v0.2.13.

I can see events being sent to GA as expected, and see the views being downloaded and other service requests firing from the route that is being navigated to, however Angulartics seems to be preventing navigation.

Any ideas?

**Comment by timelf123** [comment]
Hi @ElanHasson are you still having this problem?

**Comment by luisfarzati** [comment]
Closing old issues -- please feel free to reopen if you want to discuss this issue.
