### ISSUE TITLE
Track page view doesn't work if the automatic tracking line from your vendor snippet code is removed

### ISSUE THREAD

**Issue by iwoogy** [luisfarzati/angulartics#282]
Hello,

I notice that if I remove the automatic tracking line for GA, window.ga is undefined, and no tracking activity is sent to GA.

In the doc, it's clearly specified to remove this line :
 ga('send', 'pageview'); // <-- DELETE THIS LINE!

Can you tell me if I understood it wrong ?

Thanks

Best regards

Bobby

**Comment by DanWilkerson** [comment]
iwoogy, it's possible that the global function might have been renamed in your snippet. Window.ga is instantiated in the IIFE that loads in Google Analytics, so it should be there; check if 'ga' in the line with the arrow below has been changed to something else.

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    ->  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-XXXXXX-YY', 'auto');
    </script>

**Comment by luisfarzati** [comment]
Closing this for now, if the issue persists please feel free to reopen and comment on the case.
