### ISSUE TITLE
Adding a delay to page tracking until page is fully loaded

### ISSUE THREAD

**Issue by zackiles** [luisfarzati/angulartics#287]
I have a use case where the page html title element is dynamic, and sometimes can resolve just slightly after the page track is fired to GA. This results in a few titles that don't show in GA dashboard.

Are you open to accepting a pull request to possibly add a config value in the service provider to add delay if needed to page tracks? Or should i just fork my own version if this is too much of an edge case?

**Comment by luisfarzati** [comment]
You make a good point but I don't like the idea of adding an arbitrary delay as a solution for this problem. I'd prefer a resolve mechanism more or less in the same way that ui-router has `{ resolve: {} }` in their routes.

I'll be closing this for now, but please feel free to submit a PR for discussion!

**Comment by luisfarzati** [comment]
Closing this to avoid dupes -- let's concentrate the discussion on #112.
