### ISSUE TITLE
Question: Why rename the vendor methods?

### ISSUE THREAD

**Issue by jgentes** [luisfarzati/angulartics#291]
I'm using Mixpanel and I'm having to go into the Angulartics source to figure out how each Mixpanel method is defined. For example:

```
angulartics.waitForVendorApi('mixpanel', 500, '__loaded', function (mixpanel) {
    $analyticsProvider.registerSetUsername(function (userId) {
      mixpanel.identify(userId);
    });
  });
```

So in my code I have to use:

`$analytics.SetUsername(userid)`

rather than referencing the Mixpanel docs and using:

`$analytics.identify(userid)`

which would be more convenient.

But maybe I'm missing something?

**Comment by jgentes** [comment]
I think I get it, this way I could replace Mixpanel with something else and not have to go through and change all of my code.

**Comment by timelf123** [comment]
That's right @jgentes - we try to make things as modular as possible
