### ISSUE TITLE
Doesn't work with grunt build

### ISSUE THREAD

**Issue by rwwagner90** [luisfarzati/angulartics#294]
We are trying to use angulartics with google analytics for our site, and we get no errors locally, but after running a build, it can't seem to find the module. Can someone help please?

Errors:
## Link 1
https://docs.angularjs.org/error/$injector/nomod?p0=angulartics

## Link 2
https://docs.angularjs.org/error/$injector/modulerr?p0=angulartics&p1=Error:%20%5B$injector:nomod%5D%20Module%20%27angulartics%27%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp:%2F%2Ferrors.angularjs.org%2F1.3.12%2F$injector%2Fnomod%3Fp0%3Dangulartics%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:3:31522%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:7825%0A%20%20%20%20at%20b%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:7397)%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:7709%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:16213%0A%20%20%20%20at%20f%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:3:31907)%0A%20%20%20%20at%20n%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:15991)%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:16160%0A%20%20%20%20at%20f%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:3:31907)%0A%20%20%20%20at%20n%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:15991

## Link 3

https://docs.angularjs.org/error/$injector/modulerr?p0=bandicootApp&p1=Error:%20%5B$injector:modulerr%5D%20Failed%20to%20instantiate%20module%20angulartics%20due%20to:%0AError:%20%5B$injector:nomod%5D%20Module%20%27angulartics%27%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp:%2F%2Ferrors.angularjs.org%2F1.3.12%2F$injector%2Fnomod%3Fp0%3Dangulartics%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:3:31522%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:7825%0A%20%20%20%20at%20b%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:7397)%0A%20%20%20%20at%20b%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:7709)%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:16213%0A%20%20%20%20at%20f%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:3:31907)%0A%20%20%20%20at%20n%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:15991)%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:16160%0A%20%20%20%20at%20f%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:3:31907)%0A%20%20%20%20at%20n%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:15991)%0Ahttp:%2F%2Ferrors.angularjs.org%2F1.3.12%2F$injector%2Fmodulerr%3Fp0%3Dangulartics%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520%27angulartics%27%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.3.12%252F%2524injector%252Fnomod%253Fp0%253Dangulartics%250A%2520%2520%2520%2520at%2520http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A3%253A31522%250A%2520%2520%2520%2520at%2520http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A4%253A7825%250A%2520%2520%2520%2520at%2520b%2520(http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A4%253A7397)%250A%2520%2520%2520%2520at%2520b%2520(http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A4%253A7709)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A4%253A16213%250A%2520%2520%2520%2520at%2520f%2520(http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A3%253A31907)%250A%2520%2520%2520%2520at%2520n%2520(http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A4%253A15991)%250A%2520%2520%2520%2520at%2520http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A4%253A16160%250A%2520%2520%2520%2520at%2520f%2520(http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A3%253A31907)%250A%2520%2520%2520%2520at%2520n%2520(http%253A%252F%252F54.148.7.126%252Fscripts%252Fvendor.fc784593.js%253A4%253A15991)%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:3:31522%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:16419%0A%20%20%20%20at%20f%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:3:31907)%0A%20%20%20%20at%20n%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:15991)%0A%20%20%20%20at%20http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:16160%0A%20%20%20%20at%20f%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:3:31907)%0A%20%20%20%20at%20n%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:15991)%0A%20%20%20%20at%20Sb%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:17681)%0A%20%20%20%20at%20h%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:5510)%0A%20%20%20%20at%20_%20(http:%2F%2F54.148.7.126%2Fscripts%2Fvendor.fc784593.js:4:5820)

**Comment by troylelandshields** [comment]
I am having a similar issue.

**Comment by rwwagner90** [comment]
This appears to be an issue with ngAnnotate, I think.
