### ISSUE TITLE
Is there any AngularJS version minimum requirements?

### ISSUE THREAD

**Issue by robertochingon** [luisfarzati/angulartics#296]
Hi,

   could you please have a look at this post http://stackoverflow.com/questions/28493547/error-integrating-angulartics?noredirect=1#comment45308222_28493547.

I´m integrating angulartics and I´m getting this error: 

Uncaught TypeError: undefined is not a functionangulartics.min.js:6 (anonymous function)angular.js:2892 invokeangulartics.min.js:6 (anonymous function)angular.js:2895 invokeangular.js:2744 (anonymous function)angular.js:130 forEachangular.js:2744 createInjectorangular.js:978 resumeBootstrapInternalangular.js:993 bootstrapangular.js:954 angularInitangular.js:14843 (anonymous function)jquery-1.10.2.min.js:4 x.Callbacks.cjquery-1.10.2.min.js:4 x.Callbacks.p.fireWithjquery-1.10.2.min.js:4 x.extend.readyjquery-1.10.2.min.js:4 q

Thanks!!
Roberto.

**Comment by lunks** [comment]
The minimum angular version required for angulartics on the latest version is `1.1.5`. Update it and try again.
