### ISSUE TITLE
Add Documentation for Google Tag Manager Version 2

### ISSUE THREAD

**Issue by dyaa** [luisfarzati/angulartics#299]
Google soon will release the GTM2 after being in beta for a while so can you please update the documentation for GTM for GTM2

**Comment by xeroxoid** [comment]
+1

**Comment by carlospravia** [comment]
+1

**Comment by lunks** [comment]
We welcome PRs if anyone is interested in doing so.

**Comment by jwmarshall** [comment]
I set this up in GTM2 (where macros are variables and rules are triggers) but am having issues getting any events showing up in GA. If I can figure out the disconnect I will submit a PR.

**Comment by jwmarshall** [comment]
FWIW I was not able to get GTM2 to work and eventually reverted back to the simple GA tag.

**Comment by hppycoder** [comment]
I followed the directions on the main README and was able to get it firing. Both on the events and pageViews.

I had to specify that the Macro was a "Version 2" Macro but I think that was about it. We have been using GTM for well over a year now, so not sure if we have something configured differently. I wish I could be more help.

**Comment by dyaa** [comment]
I made it happen by doing the steps on GTM1 then export it and import the data on GTM2. 

try it guys and tell me if that solved the issue or not.

**Comment by hppycoder** [comment]
That might be what's happening. I am using the GTM UI from V1 and marking them as V2 tags.

I haven't made the switch to using the new UI yet, I guess I should. Sorry for the confusion

**Comment by stramel** [comment]
Checkout #352
