### ISSUE TITLE
Update sample code for Segment

### ISSUE THREAD

**Issue by DavidFrahm** [luisfarzati/angulartics#302]
Should we update the sample code for Segment?

Current Angulartics Segment sample code:

    var analytics = analytics || [];
    (function () {
        var e = ["identify", "track", "trackLink", "trackForm", "trackClick", "trackSubmit", "page", "pageview", "ab", "alias", "ready", "group"], t = function (e) {
            return function () {
                analytics.push([e].concat(Array.prototype.slice.call(arguments, 0)))
            }
        };
        for (var n = 0; n < e.length; n++)analytics[e[n]] = t(e[n])
    })(), analytics.load = function (e) {
        var t = document.createElement("script");
        t.type = "text/javascript", t.async = !0, t.src = ("https:" === document.location.protocol ? "https://" : "http://") + "d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/" + e + "/analytics.min.js";
        var n = document.getElementsByTagName("script")[0];
        n.parentNode.insertBefore(t, n)
    };
    analytics.load("YOUR_WRITE_KEY");

Current Segment Quickstart Analytics.js sample code:

    (function () {
    
        // Create a queue, but don't obliterate an existing one!
        var analytics = window.analytics = window.analytics || [];
    
        // If the real analytics.js is already on the page return.
        if (analytics.initialize) return;
    
        // If the snippet was invoked already show an error.
        if (analytics.invoked) {
            if (window.console && console.error) {
                console.error('Segment snippet included twice.');
            }
            return;
        }
    
        // Invoked flag, to make sure the snippet
        // is never invoked twice.
        analytics.invoked = true;
    
        // A list of the methods in Analytics.js to stub.
        analytics.methods = [
            'trackSubmit',
            'trackClick',
            'trackLink',
            'trackForm',
            'pageview',
            'identify',
            'group',
            'track',
            'ready',
            'alias',
            'page',
            'once',
            'off',
            'on'
        ];
    
        // Define a factory to create stubs. These are placeholders
        // for methods in Analytics.js so that you never have to wait
        // for it to load to actually record data. The `method` is
        // stored as the first argument, so we can replay the data.
        analytics.factory = function (method) {
            return function () {
                var args = Array.prototype.slice.call(arguments);
                args.unshift(method);
                analytics.push(args);
                return analytics;
            };
        };
    
        // For each of our methods, generate a queueing stub.
        for (var i = 0; i < analytics.methods.length; i++) {
            var key = analytics.methods[i];
            analytics[key] = analytics.factory(key);
        }
    
        // Define a method to load Analytics.js from our CDN,
        // and that will be sure to only ever load it once.
        analytics.load = function (key) {
            // Create an async script element based on your key.
            var script = document.createElement('script');
            script.type = 'text/javascript';
            script.async = true;
            script.src = ('https:' === document.location.protocol
                ? 'https://' : 'http://')
            + 'cdn.segment.com/analytics.js/v1/'
            + key + '/analytics.min.js';
    
            // Insert our script next to the first script element.
            var first = document.getElementsByTagName('script')[0];
            first.parentNode.insertBefore(script, first);
        };
    
        // Add a version to keep track of what's in the wild.
        analytics.SNIPPET_VERSION = '3.0.1';
    
        // Load Analytics.js with your key, which will automatically
        // load the tools you've enabled for your account. Boosh!
        analytics.load("YOUR_WRITE_KEY");
    
        // Make the first page call to load the integrations. If
        // you'd like to manually name or tag the page, edit or
        // move this call however you'd like.
        //analytics.page();
        // davidfrahm: Commented out since Angularlytics calls page views automagically.
    
    })();

**Comment by luisfarzati** [comment]
Yes please, if you can submit a PR with the updated code that would be great.

**Comment by luisfarzati** [comment]
This no longer belongs here -- see #390. If anyone wants to take this, please submit a PR to the [Segment plugin repo](http://github.com/angulartics/angulartics-segment).
