### ISSUE TITLE
UUID in Angulartics

### ISSUE THREAD

**Issue by fxviking** [luisfarzati/angulartics#305]
Hello,

I want to know if UUID is supported. If Yes is there any example to know how is it done. 
I am using it by injecting it in my project .  I am able to track my event (some duplicate calls are send). However i want to set a Specific UUID ,so wanted to know if its possible?

**Comment by lunks** [comment]
I don't get it, sorry. Could you clarify what do you mean by UUID support?

The app I use sends some uuids over angulartics just fine.

**Comment by timelf123** [comment]
Closing for lack up updates. Angulartics does not generate UUIDs but can send them.

There are other packages to generate UUIDs
