### ISSUE TITLE
Google Tag Manager question

### ISSUE THREAD

**Issue by streetdaddy** [luisfarzati/angulartics#306]
I've setup the Tags, Macros and Rules, as per the documentation.  I'm seeing page views, but should I automatically be seeing any interaction events as well?  

Or do I need to set them up separately ie. by adding programatic or declarative tracking in my app?

Apologies if there is an explanation or docs that I've missed...

**Comment by carlospravia** [comment]
You should add the events you need to track using the declarative tracking on each button or interactive object.
