### ISSUE TITLE
Does angulartics-ga need waitForVendorApi?

### ISSUE THREAD

**Issue by glorat** [luisfarzati/angulartics#309]
Per the code comments
// GA already supports buffered invocations so we don't need
// to wrap these inside angulartics.waitForVendorApi
For the _gaq flavour, this certainly seems true since we are only pushing into an array. But for the universal ga flavour, where does ga get defined before until the analytics.js is loaded? Won't events before the js load get dropped?

**Comment by luisfarzati** [comment]
I understand universal implements buffering as well. Closing for now -- but please feel free to reopen if you have issues with this.
