### ISSUE TITLE
Export the module name

### ISSUE THREAD

**Issue by kentcdodds** [luisfarzati/angulartics#311]
See [my post](https://medium.com/@kentcdodds/how-to-distribute-your-angularjs-module-e04d4dd58ddc) about it and [this angular.js PR comment](https://github.com/angular/angular.js/pull/10732#issuecomment-74986139) for reasons as to why it's a good idea. Basically, enables this:

```javascript
angular.module('myModule', [
  require('angulartics'),
  require('angulartics/src/angulartics-ga')
]);
```

That would be really nice. Thanks!

**Comment by luisfarzati** [comment]
As commented in #374 and #377, plugins are being moved to their own repo and *npmified* in the process. Google Analytics is already there: https://github.com/angulartics/angulartics-google-analytics

Thanks for the suggestion!
