### ISSUE TITLE
Angulartics No Longer Actively Maintained

### ISSUE THREAD

**Issue by leore** [luisfarzati/angulartics#314]
Is this module being actively maintained anymore?

**Comment by leore** [comment]
Looks like no one is maintaining this repo...

**Comment by epelc** [comment]
Was just about to use this too. Are there any other alternatives?

**Comment by leore** [comment]
I dunno. But its a shame as this was really close to what I needed.

**Comment by lunks** [comment]
We're trying to keep this maintained, folks. :)
https://twitter.com/luisfarzati/status/577552657864400896
Feel free to help with older issues/PRs, check if they are still valid/working.

**Comment by leore** [comment]
@lunks our team at lob.com would be happy to help and contribute a maintainer.

**Comment by lunks** [comment]
Could you ping Luis over Twitter?

**Comment by luisfarzati** [comment]
Hey there, let me know which GitHub account(s) should I give access and I'll happily do that.

Thanks!

**Comment by leore** [comment]
Add @pon and @leore

**Comment by luisfarzati** [comment]
Done!
