### ISSUE TITLE
Use same tracking information for multiple domains or subdomains, how can we do it ?

### ISSUE THREAD

**Issue by HadrienPierart** [luisfarzati/angulartics#320]
Most of the point is in the question. The Google Analytics doc seems to suggest to use the linker attribute at setup but I don't see how to use it with your lib...
Some tips would be much appreciated.
Thx

**Comment by timelf123** [comment]
Can you explain a bit more about your setup?

**Comment by luisfarzati** [comment]
Closing for now. Please feel free to reopen if willing to share more about your setup.
