### ISSUE TITLE
angulartics not works with angular 1.3.x

### ISSUE THREAD

**Issue by szabobar** [luisfarzati/angulartics#323]
Hi,

I got a problem. The sample apps (google analytics) works with angular v1.1.5.

After I changed the version to 1.3.x (and fixed angular-route dependency) the sample does not send request to Google analytics server. (and if I would like to implement it to my project the result was the same)

Thanks

**Comment by lunks** [comment]
I'm using it on an Angular 1.3.2 project just fine.

**Comment by zxkane** [comment]
Failed to try **sample/google-analytics.html** when using angular 1.3.15.

```
Uncaught Error: [$injector:modulerr]
```

**Comment by hppycoder** [comment]
We are using it for over 4 weeks in a project of ours in production. It works just fine. Can you post your app.js file so we can look at it? Also what's the full error?

**Comment by mlaurel** [comment]
I'm also having issues when using Angular 1.2.15 or anything above.  Here is a snippet of my app.js file below.  Why doesn't the sample file use a more updated version of Angular... version 1.1.5 seems a bit old.  

var app = angular.module('appName', [
    'ngRoute', 'ngResource', 'ngAnimate', 'ngSanitize', ['angulartics', 'angulartics.google.analytics']
]);

// ---------- Routes ----------

app.config(['$routeProvider',
    function ($routeProvider) {
        $routeProvider
            .when('/pageA', {
                templateUrl: 'partials/pageA.html',
                controller: ''
            })
            .when('/pageB', {
                templateUrl: 'partials/pageB.html',
                controller: ''
            }) 
            .otherwise({
                redirectTo: '/home'
            });
}]);

**Comment by luisfarzati** [comment]
Closing for now. @zxkane please feel free to share a jsfiddle and reopen this if you still have this issue.
