### ISSUE TITLE
First Page View/ Session Not recorded

### ISSUE THREAD

**Issue by nukulb** [luisfarzati/angulartics#330]
After commenting out the following line, as the instructions suggest
// Google Analytics example
ga('send', 'pageview'); // <---- delete this line!

My first page view and session are not recorded!

As in I land on a page, and it won't be recorded as a session or as a page view. After the first page, all other pages get recorded appropriately.

**Comment by DanWilkerson** [comment]
nukulb, try adjusting your configuration to fire the first pageview, a la:

    var yourApp = angular.module('YourApp', ['angulartics', 'angulartics.google.analytics'])
        .config(function ($analyticsProvider) {
            $analyticsProvider.firstPageview(true); /* Records pages that don't use $state or $route */
            $analyticsProvider.withAutoBase(true);  /* Records full path */
    });

You are correct that because there is no initial pageview, your user session doesn't start until they generate a pageview or event.

**Comment by luisfarzati** [comment]
Closing for now, feel free to reopen if the issue persists.
