### ISSUE TITLE
Allowing 0 as a value in GA

### ISSUE THREAD

**Issue by birge** [luisfarzati/angulartics#332]
I am not sure if this is the intended behavior but, when you set the analytics.value to any number other than 0 it will send through. If you enter 0 however, the request won't any value attached.

**Comment by lunks** [comment]
Not sure if we are doing anything fancy. Perhaps this is a problem on GA's side? Could you try tracking 0 values without angulartics and check if this is still an issue?

**Comment by birge** [comment]
Found it in the GA module, created a PR

https://github.com/luisfarzati/angulartics/pull/335
