### ISSUE TITLE
Google Tag Manager and Analytics setup

### ISSUE THREAD

**Issue by carlospravia** [luisfarzati/angulartics#333]
Hello, I setup a basic sample tab app using ionic framework. 

On this app I added the angulartics support for GTM and added the $analyticsProvider on the config method.

On GTM I'm using the debug mode and I see the 'Angulartics Pageviews' tag fired during the 'content-view' event. The 'angulartics page path' macro is correctly defined and have the correct value for every app screen. 

Finally, on GA I'm pending of the real-time report for any sign of interaction, but there is non.

I tried with both a GA app property and a web property but in both cases I don't see any interaction.

Someone with the same problem using the GTM vendor?

I'm using AngularJS 1.3.x

**Comment by DanWilkerson** [comment]
carlospravia, did you just create your GA account? It can take a few hours before data shows up in the realtime reports. Also, do you have a filter blocking your offices IP addresses? That would filter out your hits from the view you are looking at. Finally, make sure that the UA number you're sending the hits with (the Tracking ID field in the GTM interface) matches the one on your Property. It should be visible in the top right of the Google Analytics interface.

**Comment by luisfarzati** [comment]
Closing for now. Please feel free to reopen if necessary.
