### ISSUE TITLE
Method "withBase" fails because jqLite doesn't support looking up elements via selectors

### ISSUE THREAD

**Issue by mladenplavsic** [luisfarzati/angulartics#341]
Method "withBase" asks for 

    angular.element('base').attr('href').slice(0, -1)

This fails becuase looking up elements via selectors is not supported by jqLite (http://docs.angularjs.org/api/angular.element)

Solution is to get "base" element with something like

    angular.element(document.getElementsByTagName('base')[0]).attr('href').slice(0, -1)

Or with some conditional statements which check if "base" really exist.

**Comment by jacquesdancona** [comment]
+1

**Comment by mediavrog** [comment]
+1
