### ISSUE TITLE
GTM v2 - no events triggered at all

### ISSUE THREAD

**Issue by xeroxoid** [luisfarzati/angulartics#342]
Hey,

I am banging my head for some days now (and it hasn't helped indeed) to get angulartics to work with GTM v2. I have set it up as per the github description translating rules->triggers and macros->variables. My problem is that no single event is fired (that I can see on the network tab on Chrome console) ever. My setup ensures the following:

-Both angulartics.js and angulartics-gtm.js are loaded/included
-The gtm snippet is correct and my GTM-XXXX id correctly set on both occurances
-'angulartics' and 'angulartics.google.tagmanager' are injected to the app/main module
-Tried setting $analyticsProvider.withBase(true); and $analyticsProvider.firstPageview(true); just in case (yes I use <base href="/">)

Still nothing seems to ever get fired... any clues?

Angular version: 1.3.14

**Comment by xeroxoid** [comment]
I think that this seems to be the problem... but can't find why this is happening.

![Screenshot](http://i.imgur.com/C7MzPyg.png)

**Comment by dkeza** [comment]
I have same problem. I am using angulartics/samples/google-tag-manager.html example, and when I insert my google tag manager snippet, only my content is updated in Google Analytics, but no event fires.
I have set up google tag manager tags rules and macros as described here https://github.com/luisfarzati/angulartics#for-google-tag-manager

When I try it with direct with angulartics/samples/google-analytics.html, and insert my Googla Analytics snippet, events are fired.

**Comment by xeroxoid** [comment]
I know.. as noted here: https://gitter.im/luisfarzati/angulartics# it seems that v2 is not supported yet. I did a custom solution for pageViews at least for now. Let me know if you need something similar.

**Comment by thinq4yourself** [comment]
@xeroxoid - How exactly did you get to register events using PageViews in version 2? Any help is appreciated. Also, quick question...

For `Angulartics events` Trigger, I have it setup as a Custom Event that fires on Event name=`interaction` and Fire this trigger when all of these conditions are true = `event contains interaction`. Is this correct in V2? Screenshot below and thanks in advance.

![screenshot 2015-05-01 at 10 27 00](https://cloud.githubusercontent.com/assets/147231/7431439/ab6d8c74-efec-11e4-94f5-2bbb2431ac80.png)

**Comment by DanWilkerson** [comment]
xeroxoid - remove the condition you've added for 'Event' to match 'interaction' and it will work. The **Event name** is the field GTM uses to match against the event value pushed to the Data Layer. You or someone else created the **Event** (note case) variable, which is probably configured differently and is unnecessary. Check out [#352](https://github.com/luisfarzati/angulartics/pull/352) for more detailed instructions. Let me know if it doesn't fix the problem.

thinq4yourself - remove the condition you've added for event contains interaction. The **Event name** field above is all you need; GTM looks to match any events it seems with the name you provide, in this case interaction.

**Comment by xeroxoid** [comment]
Seems to be working now, thanks. At some point I even got it working with the extra condition.

**Comment by b3ckstage** [comment]
![lir_portal_ _ripe_network_coordination_centre](https://cloud.githubusercontent.com/assets/1614510/13754952/316115fe-ea19-11e5-8828-8c0b66fa3878.jpg)


Any idea how can I trigger event 'interaction'?

**Comment by Debananda** [comment]
This is not working for me either. I have raised an issue https://github.com/angulartics/angulartics-google-tag-manager/issues/23

**Comment by DanWilkerson** [comment]
Are you either using the directive for event tracking or calling $analytics.eventTrack() somewhere in your code?
