### ISSUE TITLE
Implementing user ID with google tag manager

### ISSUE THREAD

**Issue by lwensveen** [luisfarzati/angulartics#349]
Hey,

I'm running into some problems whilst trying to implement the tracking of a user ID.

So far I've came up with pushing my user ID (which is available after a user signs in) to the dataLayer when a user logs in.

Now is this the preferred way to do this?

Or is there another way?

Thanks in advance

**Comment by hermanocabral** [comment]
+1

**Comment by DanWilkerson** [comment]
This seems to me like the right way to do this. You'll need to add the **userId** 'Field to Set' and pipe in the value of that Data Layer Variable with a Variable, and you'll need to add that to **every** Google Analytics tag in your container. In v2:

![screen shot 2015-05-09 at 10 16 52 am](https://cloud.githubusercontent.com/assets/5819661/7550560/a1830ab0-f634-11e4-8cad-cd0cbbf0d30a.png)

If you're on v1, this will be here:

![screen shot 2015-05-09 at 10 20 21 am](https://cloud.githubusercontent.com/assets/5819661/7550576/1161ed56-f635-11e4-96f9-6e30b149409a.png)


If you don't set that field on a particular tag, those hits will be excluded from the User ID view, per [https://developers.google.com/analytics/devguides/platform/user-id#processing](https://developers.google.com/analytics/devguides/platform/user-id#processing). If this value is anything other than undefined or an empty string, it will be coerced into a User ID, which is super not great. Make sure that your Variable returns undefined if there is no User ID available.

Finally, you'll need a User-ID Enabled View in your Property. In Google Analytics, click Admin, select Tracking Info under the middle column, and click User ID. Agree to the terms and configure your view.

**Comment by stramel** [comment]
@DanWilkerson :+1: That is the way that I found to do it as well.

**Comment by luisfarzati** [comment]
I think this can be closed now, right? Feel free to reopen otherwise.
