### ISSUE TITLE
Stuck for hours. Cordova: Value null at 3 of type org.json.JSONObject$1 cannot be converted to long 

### ISSUE THREAD

**Issue by khinze** [luisfarzati/angulartics#351]
Hi, 

I am trying to get event tracking to work in my cordova app.

The error I get when executing:
    $analytics.eventTrack('HomePage', {  category: 'HomePage', label: 'user navigated to home page. ', value:1 });
    console.log('should fire event')
    $analytics.eventTrack('Why', {   category: 'HomePage', label: 'user navigated to home page. ' })

is: 
Value null at 3 of type org.json.JSONObject$1 cannot be converted to long vendor.7529bcf2.js:6
(anonymous function) vendor.7529bcf2.js:6
h vendor.7529bcf2.js:12
cordova.callbackFromNative cordova.js:295
processMessage cordova.js:1054
androidExec.processMessages

My settings in my app.js are as follows:
 googleAnalyticsCordovaProvider.trackingId = 'my tracking id';
    googleAnalyticsCordovaProvider.debug = true;
    googleAnalyticsCordovaProvider.period = 20; 
    $analyticsProvider.virtualPageviews(false); 
   
All I get when I go to google analytics is / pageviews. 

Furthermore when I add the following to a button click the event also does not show up on google analytics: 
*** class="btn btn-primary btn-lg btn-block active center-block" href="#login" analytics-on="click" analytics-event="Login" analytics-category="Login" analytics-label="User navigating to login page.">Login***

I really appreaciate it if someone can tell me where I am going wrong. Been stuck for hours.

**Comment by khinze** [comment]
analytics-event="Login" analytics-category="Login" analytics-label="User navigating to login page."

**Comment by timelf123** [comment]
I have not attempted to use this with cordova, sorry. Did you check out the cordova sample files?

Also, it's usually not best practice to track pageviews as events. I would recommend using the `pageTrack` method
