### ISSUE TITLE
directive analytics-on="scrollby" does not work

### ISSUE THREAD

**Issue by mrbatista** [luisfarzati/angulartics#353]
I cannot track scrollby events. It seems that the issue is caused by an incorrect reading of the attributes.
![bug angulartics-scroll2](https://cloud.githubusercontent.com/assets/6544817/7681555/63d875a8-fd71-11e4-847d-30d5921b07ef.png)

**Comment by mrbatista** [comment]
Any help?

**Comment by corinna000** [comment]
Can you provide a jsfiddle or repository showing this behavior? Thanks

**Comment by luisfarzati** [comment]
Closing for now -- @mrbatista if you still have this issue please share a jsfiddle so we can check it out! Thanks.
