### ISSUE TITLE
Bump npm version

### ISSUE THREAD

**Issue by robinjoseph08** [luisfarzati/angulartics#354]
There are several features that have been merged to master that would be very useful to me, but the npm version hasn't been bumped in 4 months. Is there a reason why it's still on the same version? I can refer to the master branch for my projects for now, but I would like it to published.

Thanks.

**Comment by lunks** [comment]
I'd like it to be published as well. I've been trying to keep merging those
PRs up and release a new version. Unfortunately I'm not getting the time
I'd like to for open source projects. :( Please keep pointing your projects
to master for now and wait a little bit for a new version. Thanks! :)

**Comment by robinjoseph08** [comment]
Totally understandable :) We heavily use this this module at Lob with @leore and @pon, and I would be more than happy to help you out in anyway I can!

**Comment by lunks** [comment]
Done!
