### ISSUE TITLE
Update documentation for new Google Tag Manager user interface

### ISSUE THREAD

**Issue by sashton-stoneware** [luisfarzati/angulartics#365]
The documentation in readme.md for configuring angulartics to work with Google Tag Manager is out of date. For instance, the new Tag Manager user interface has replaced "rules" with "triggers" with slightly different behavior as explained here: http://www.simoahava.com/analytics/trigger-guide-google-tag-manager/

Also, "macros" have been replaced with "variables", although I think this change is simply a name change. Although the new interface does ask us to specify a "data layer version" which the current documentation does not talk about.

This is pretty important for a n00b like me who is trying to get this all configured. Thanks!

**Comment by achinth** [comment]
+1

**Comment by jfmengels** [comment]
+1

I can manage the name changes (macros vs variables, etc.), but some thingsseem to have disappeared / changed on a bigger scale. Even by adapting the name changes, I can't seem to follow this step from the readme anymore (as "Basic configuration" seems to have disappeared from "More Settings") :

- Tag Name: Angulartics Pageviews
    - Tag Type: Universal Analytics
    - Tracking ID: YourGoogleAnalyticsID
    - Track Type: Page View
    - More settings
        - Basic Confiruration
            - Document Path: {{angulartics page path}}
    - Firing Rules: Angulartics pageviews

If someone could help me figure this one out, and update the documentation, I'd be pretty grateful.

**Comment by seyDoggy** [comment]
+1 This is killing me.

**Comment by seyDoggy** [comment]
Until my PR get's merged, here are the updated docs for the new GTM interface:

## for Google Tag Manager (new interface)

    angular.module('myApp', ['angulartics', 'angulartics.google.tagmanager'])
    
Add the full tracking code from Google Tag Manager to the beginning of your body tag.

Setup listeners in Google Tag Manager

#### 6 Variables

Naming and case must match.

1. **angulartics page path**   
    Type: **Data Layer Variable**    
    Data Layer Variable Name: **content-name**
2. **angulartics event category**    
    Type: **Data Layer Variable**   
    Data Layer Variable Name: **target**
3. **angulartics event action**   
    Type: **Data Layer Variable**   
    Data Layer Variable Name: **action**
4. **angulartics event label**   
    Type: **Data Layer Variable**   
    Data Layer Variable Name: **target-properties**
5. **angulartics event value**   
    Macro Type: **Data Layer Variable**   
    Data Layer Variable Name: **value**
6. **angulartics event interaction type**    
    Type: **Data Layer Variable**   
    Data Layer Variable Name: **interaction-type**

#### 2 Triggers

Name and case must match

1. **Angulartics events**    
    Event: **Custom Event**    
    Fire on: **interaction**
2. **Angulartics pageviews**    
    Event: **Custom Event**    
    Fire on: **content-view**

#### 2 Tags

1. **Angulartics Events**    
    Product: **Google Analytics**    
    Type: **Universal Analytics**   
    Tracking ID: **YourGoogleAnalyticsID**   
    Track Type: **Event**
    Category: **{{angulartics event category}}**   
    Action: **{{angulartics event action}}**   
    Label: **{{angulartics event label}}**   
    Value: **{{angulartics event value}}**   
    Non-Interaction Hit: **{{angulartics event interaction type}}**   
    Fire On: **Angulartics events**
2. **Angulartics Pageviews**   
    Product: **Google Analytics**   
    Type: **Universal Analytics**   
    Tracking ID: **YourGoogleAnalyticsID**   
    Track Type: **Page View**    
    More settings > Field to Set > name: **page**, value: **{{angulartics page path}}**   
    Fire On: **Angulartics pageviews**

**Comment by jfmengels** [comment]
@seyDoggy that seems to work just fine, thanks a lot!

**Comment by luisfarzati** [comment]
Merged. Thanks!
