### ISSUE TITLE
minimified files failed on usage

### ISSUE THREAD

**Issue by mathieuyocto** [luisfarzati/angulartics#374]
Hi,

angulartics.min.js and angulartics-ga.min.js failed on usage.
We got angular injector error.

After use ng-annotate & uglify on these two files its works perfectly. So I think that angulartics.min.js and angulartics-ga.min.js have builing error.

**Comment by timelf123** [comment]
Thanks for reporting. I'll add ng-annotate to our build process as part of the next release

**Comment by varmint09** [comment]
+1 when will this be ready for release?

I use npm as my package manager not bower, and the gulp/browserify/uglify process needs this.

Many thanks

**Comment by timelf123** [comment]
Hoping to cut a release this week

**Comment by varmint09** [comment]
*bump!* Sorry, but this excellent plugin will surely get far more use when it allows npm installs.

**Comment by luisfarzati** [comment]
@varmint09 We are moving each plugin into their own repo and during the process we are now packaging for npm as well as bower: see [angulartics-google-analytics](https://github.com/angulartics/angulartics-google-analytics). 

The rest of the plugins will be moved as well during the next few weeks.

Let us know if you run into any issues.

**Comment by luisfarzati** [comment]
@mathieuyocto please try again, if the issue persists there's still the chance that the core has build problems. Hopefully @timelf123 will be including this in the next release.
