### ISSUE TITLE
All vendors included by bower-install

### ISSUE THREAD

**Issue by TheWrongAlice** [luisfarzati/angulartics#377]
I use `bower-install` to inject script tags into my index.html file.

When setting up angulartics, I used `bower install --save angulartics` and then added to my angular app:
```
angular.module('sobazaar', [
  ...
  'angulartics',
  'angulartics.google.analytics'
])
```

But all of these vendors were added to my index.html:
```
    <script src="bower_components/waypoints/lib/noframework.waypoints.min.js"></script>
    <script src="bower_components/SHA-1/sha1.js"></script>
    <script src="bower_components/angulartics/src/angulartics.js"></script>
    <script src="bower_components/angulartics/src/angulartics-adobe.js"></script>
    <script src="bower_components/angulartics/src/angulartics-chartbeat.js"></script>
    <script src="bower_components/angulartics/src/angulartics-clicky.js"></script>
    <script src="bower_components/angulartics/src/angulartics-cnzz.js"></script>
    <script src="bower_components/angulartics/src/angulartics-flurry.js"></script>
    <script src="bower_components/angulartics/src/angulartics-ga-cordova.js"></script>
    <script src="bower_components/angulartics/src/angulartics-ga.js"></script>
    <script src="bower_components/angulartics/src/angulartics-gtm.js"></script>
    <script src="bower_components/angulartics/src/angulartics-kissmetrics.js"></script>
    <script src="bower_components/angulartics/src/angulartics-mixpanel.js"></script>
    <script src="bower_components/angulartics/src/angulartics-piwik.js"></script>
    <script src="bower_components/angulartics/src/angulartics-scroll.js"></script>
    <script src="bower_components/angulartics/src/angulartics-segmentio.js"></script>
    <script src="bower_components/angulartics/src/angulartics-splunk.js"></script>
    <script src="bower_components/angulartics/src/angulartics-woopra.js"></script>
    <script src="bower_components/angulartics/src/angulartics-marketo.js"></script>
    <script src="bower_components/angulartics/src/angulartics-intercom.js"></script>
    <script src="bower_components/angulartics/src/angulartics-inspectlet.js"></script>
    <script src="bower_components/angulartics/src/angulartics-newrelic-insights.js"></script>
```
...and obviously I don't want all of that, I just want the base lib + google analytics.

How can I make sure that the vendors I don't use are not included by `bower-install`?

**Comment by TheWrongAlice** [comment]
Also what is this exactly? It seems to have been added when I installed angulartics.
```
    <script src="bower_components/waypoints/lib/noframework.waypoints.min.js"></script>
    <script src="bower_components/SHA-1/sha1.js"></script>
```

**Comment by TheWrongAlice** [comment]
@luisfarzati perhaps you would know? :)
Any advice would be greatly appreciated

**Comment by luisfarzati** [comment]
@TheWrongAlice splitting off the plugins is still a pending task. Until then, unfortunately everything is bundled in the package.

It seems you have some build task that automatically injects your bower dependencies in your index.html file, so this is a problem indeed. I think a temporary solution for this may be https://github.com/blittle/bower-installer, check it out.

Regarding the libraries you mention, waypoints enables the [scroll tracking feature](http://luisfarzati.github.io/angulartics/#/scroll-tracking) and, as of the rest of the plugins, this is included by default as well.

I'm not sure about sha1.js, that may be included in the last merges. Perhaps @timelf123 or @lunks know better.

**Comment by luisfarzati** [comment]
Ok @TheWrongAlice, the gods have heard and I'm in the process of splitting the plugins off the core. See [angulartics-google-analytics](http://github.com/angulartics/angulartics-google-analytics).

We'll be doing the same with the rest of the plugins during the following weeks.

**Comment by TheWrongAlice** [comment]
Thanks! :D
I will try it tonight

**Comment by timelf123** [comment]
Closed by https://github.com/angulartics/angulartics/pull/411
