### ISSUE TITLE
Clarify Versioning Strategy

### ISSUE THREAD

**Issue by andrewaustin** [luisfarzati/angulartics#385]
The change on 7/23 to move the plugins to a different repo does not follow semantic versioning. Can you clarify how you are versioning angulartics? 

Specifically, you moved angulartics-ga.min.js but only bumped a minor version. Since bower by default has ~19.0 this caused breaking issues.

**Comment by 4storia** [comment]
+1

**Comment by lunks** [comment]
Whoops. We should really have upgraded the major version cc @luisfarzati. Our apologies.

**Comment by luisfarzati** [comment]
Yeap, nothing to clarify, other [than stupidity on my part](https://github.com/luisfarzati/angulartics/pull/132#issuecomment-41177942). Should we still rebump anyway, @lunks @timelf123?

**Comment by lunks** [comment]
We should yank the latest version if possible and do a major bump.

**Comment by mindmelting** [comment]
My build broke because of this :(

**Comment by lunks** [comment]
Hey, I just released 0.19.3 which reverts the splitting. Feel free to upgrade to it and keep things sane, folks. Sorry for the previously broken release. 0.20.0 has been released with the removed plugins.
