### ISSUE TITLE
angulartics-ga.js Removed from 0.19.2

### ISSUE THREAD

**Issue by mfoody** [luisfarzati/angulartics#386]
The issue I have is that it was done in a point release. Bower auto-updated from 0.19.0 to 0.19.2 and everything stopped working since the file had been removed. It might be too late to do anything now but in the future can these changes be made in a minor version release instead of a patch release?

**Comment by mfoody** [comment]
Just saw this was already submitted in 385.

**Comment by luisfarzati** [comment]
Yeap, sorry for that. My bad. It should definitely have been a minor or even a major (although no API changes in the core, having plugins embedded in the core could easily be seen as part of the API).

**Comment by seadour** [comment]
@luisfarzati Sorry, can you clarify why angulartics-ga.js was removed but various other plugins (clicky, cnzz, ga-cordova) remain? Where can I find angulartics-ga now?

**Comment by luisfarzati** [comment]
The plugins are being moved progressively. Some of them are moved, some of
them not yet.

You can find those already moved in the new Angulartics org,
http://github.com/angulartics -- e.g., you can find GA at
http://github.com/angulartics/angulartics-google-analytics

**Comment by seadour** [comment]
Thank you

**Comment by lunks** [comment]
Hey folks, just use 0.19.3 which reverts the splitting. 0.20.0 is where you should be if you want the latest and greatest, but be sure to add the appropriate plugins which have been split.

Thanks!
