### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by thetif** [luisfarzati/angulartics#387]
the newest release is missing this file angulartics/dist/angulartics-ga.min.js. Is there a new file I should be using or was this a mistake?

**Comment by lunks** [comment]
Which releae are you talking about, 0.19.3 or 0.20.0?

**Comment by thetif** [comment]
0.20.0

**Comment by lunks** [comment]
For 0.20.0 you should require the angulartics-google-analytics package which contains the google analytics plugin. We're slowly removing plugins to their own repos so it's easier to maintain angulartics.

**Comment by thetif** [comment]
Great, thanks!
