### ISSUE TITLE
Possible to use multiple backends

### ISSUE THREAD

**Issue by mdedetrich** [luisfarzati/angulartics#389]
This is more of a general question, but is it possible for `angulartics` to support multiple backends? At our marketing department, we have requests to support both `google-analytics` and `mixpanel`, it would be greatly beneficial if we could just reuse the current analytics tags we have for `google-analytics`  with `mixpanel`

**Comment by timelf123** [comment]
Yes it is possible. Just add dependencies to all the providers you wish to send calls to, and one call to angulartics.pageTrack will send the calls to all providers

**Comment by mdedetrich** [comment]
Cool, thank you confirming this!

**Comment by luisfarzati** [comment]
I think we can close this now :)

**Comment by mdedetrich** [comment]
Yup, will comment here again if I come across any issues
