### ISSUE TITLE
Sample links broken

### ISSUE THREAD

**Issue by filipesilva** [luisfarzati/angulartics#398]
Hi,

It seems the sample links on the [angulartics webpage](http://luisfarzati.github.io/angulartics/), such as the one for mixpanel (`http://angulartics.herokuapp.com/mixpanel.html`) are broken. 

Are those examples still up somewhere?

**Comment by luisfarzati** [comment]
Samples are under the new Angulartics org, https://github.com/angulartics/angulartics-mixpanel -- the website needs to be updated, though. Thanks.

**Comment by ProLoser** [comment]
@filipesilva Hey man, I transferred the website to here: https://github.com/angulartics/angulartics.github.io hopefully it may be easier to make a PR (even using the Github.com interface) and would really help us out while we transfer things over.

I'm going to close this issue for now as that repo has it's own issue tracker.
